### ISSUE TITLE
Setup Dependabot for Rust dependencies

### ISSUE THREAD

**Issue by hiltontj** [hiltontj/serde_json_path#96]
A section needs to be added to the [`.github/dependabot.yml`](https://github.com/hiltontj/serde_json_path/blob/6a6410fe9eb889f6e605c9f73af2474ad17b05d5/.github/dependabot.yml) file to manage Rust dependencies, e.g.,
```yml
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - "hiltontj"
  commit-message:
    prefix: "chore"
    include: "scope"
  rebase-strategy: "disabled"
```
